# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1cf79da10c0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.65661496 0.06421729 0.29511418]
 [0.81403733 0.29306227 0.32764402]
 [0.04789612 0.10183695 0.90527237]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.65661496 0.06421729 0.29511418]
 [0.81403733 0.29306227 0.32764402]
 [0.04789612 0.10183695 0.90527237]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
print(arr1_1)
np.info(arr1_1)

[[0.42244669 0.91700347 0.01931199 0.24836486]
 [0.54621797 0.7878906  0.77718025 0.36927157]
 [0.17593753 0.17792279 0.97720846 0.40805893]]
class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1cf79a70870
byteorder:  little
byteswap:  False
type: float64


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['IT','Buisness','Medicine','Building','Ecology'])
print(arr1_2)

['IT' 'Buisness' 'Medicine' 'Building' 'Ecology']


In [32]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4), dtype='float64')
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array([False] * 9)
arr2_1 = arr2_1.reshape((3, 1, 3))
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [20]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3, 3)
arr2_2 = arr2_2.astype('int')
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2)  
arr2_3 = arr2_3.reshape((2,3))
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [24]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [25]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[36 17 28 13]
 [43 49 23 31]
 [14 48 35 43]
 [16 21 32 32]]


In [26]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

31


In [27]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[16 21 32 32]


In [28]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[36 17 28 13]
 [43 49 23 31]]


In [29]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[17 28]
 [49 23]
 [48 35]
 [21 32]]


In [30]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[36 17 28 13]
 [14 48 35 43]]


In [31]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[36 28 43 49 23 31 48 35 43 21 32 32]


### ЗАВДАННЯ 3

In [33]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[58 85 22 38 56]
 [44 79 12 41 84]
 [50 29 12 94 56]
 [51 33 93 23 72]]


In [34]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

12


In [35]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[44 79 12 41 84]


In [36]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4,2:3]
print(vect3_4)

[[22]
 [12]
 [12]
 [93]]


In [37]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3,1:3]
print(mat3_5)

[[79 12]
 [29 12]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [38]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [40]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.87202789 0.5245319  0.1799802  0.08237623 0.74923005]
 [0.63454211 0.16201711 0.73836773 0.32790449 0.81429608]
 [0.79260701 0.88622972 0.91271923 0.57972826 0.44309306]
 [0.97090244 0.63709193 0.01807996 0.0843736  0.42327015]
 [0.77443587 0.76291018 0.04329336 0.27845173 0.74619965]]
...
[0.87202789 0.16201711 0.91271923 0.0843736  0.74619965]


In [41]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.87202789 0.63454211 0.79260701 0.97090244 0.77443587]
 [0.5245319  0.16201711 0.88622972 0.63709193 0.76291018]
 [0.1799802  0.73836773 0.91271923 0.01807996 0.04329336]
 [0.08237623 0.32790449 0.57972826 0.0843736  0.27845173]
 [0.74923005 0.81429608 0.44309306 0.42327015 0.74619965]]


In [42]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.03303348232489012


In [43]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-2.66741202  1.52068289 -0.74931902  3.42628754 -0.47977514]
 [ 3.86178383 -2.73152569  1.51413382 -2.71573356 -0.2553031 ]
 [ 3.24122114 -0.86079988  1.28668138 -1.7221447  -2.10220074]
 [-8.83337149  3.4771429  -1.32223195  3.77420263  3.71906906]
 [ 1.92829035 -0.03311737 -0.35161577 -2.08785278  0.83323345]]


### ЗАВАДАННЯ 4

In [44]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100,200,(6,6))
print(mat4_1)

[[191 132 178 118 134 105]
 [191 115 177 192 181 184]
 [114 186 168 165 162 103]
 [140 185 123 149 126 136]
 [178 170 143 105 143 124]
 [172 134 102 116 161 195]]


In [45]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[191 115 168 149 143 195]


In [46]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[191 191 114 140 178 172]
 [132 115 186 185 170 134]
 [178 177 168 123 143 102]
 [118 192 165 149 105 116]
 [134 181 162 126 143 161]
 [105 184 103 136 124 195]]


In [48]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-0.06164442  0.04632746 -0.02869563 -0.005708    0.09491798 -0.05174092]
 [ 0.00621699 -0.01209518  0.00314805  0.00814089 -0.00729346  0.00536261]
 [ 0.10912106 -0.06898263  0.0317084   0.01125966 -0.14157273  0.07175811]
 [-0.05846165  0.04628357 -0.01904007  0.0031797   0.06994906 -0.04883435]
 [-0.07378534  0.04408569 -0.00444549 -0.0314541   0.09802822 -0.03991878]
 [ 0.08872004 -0.06040016  0.02155859  0.01762912 -0.12720403  0.07155503]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [49]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [50]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [51]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [52]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [53]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [54]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [55]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [56]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [57]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


<ipython-input-57-df0164db1db1>:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [58]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [59]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [60]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [61]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [62]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [63]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[8 5 7 6 2]
[8 5 7 6 2]
1990656365168 1990656365168
[8 5 7 6 2]
1990656365168 1990656364784


In [64]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [67]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(4, 3)
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[0.9400233  0.26963936 0.25171514]
 [0.13546562 0.55473385 0.34998161]
 [0.53218127 0.93329297 0.17995671]
 [0.01793192 0.9624211  0.28488391]]
[1.46137779 1.04018109 1.64543095 1.26523693]


In [68]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

1.0401810870978287


In [69]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[100.9400233  100.26963936 100.25171514]
 [100.13546562 100.55473385 100.34998161]
 [100.53218127 100.93329297 100.17995671]
 [100.01793192 100.9624211  100.28488391]]


In [70]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.multiply(mat5_1, np.diag(mat5_3))
print(mat5_4)

[[94.88597346 27.11351401 25.21681142]
 [13.67390309 55.781115   35.06114265]
 [53.71838939 93.84702623 18.02805531]
 [ 1.810048   96.77599723 28.53965808]]


In [72]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print('Ранг отриманої матриці : ',np.linalg.matrix_rank(mat5_5))

[[100.9400233  100.26963936 100.25171514  94.88597346  27.11351401
   25.21681142]
 [100.13546562 100.55473385 100.34998161  13.67390309  55.781115
   35.06114265]
 [100.53218127 100.93329297 100.17995671  53.71838939  93.84702623
   18.02805531]
 [100.01793192 100.9624211  100.28488391   1.810048    96.77599723
   28.53965808]]
Ранг отриманої матриці :  4
